config/routes.rb
Sms::Engine.routes.draw do
  resource :config, only: [:show, :new, :create, :edit, :update]

  resources :messages, only: [] do 
    post :resend, on: :member
    post :cancel, on: :member
  end

  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      post "api_sms_status_response", to: "messages#api_sms_status_response"
      post "api_sms_response", to: "responses#api_sms_response"
    end
  end

  get "log", to: "log#index"
end

app/models/concerns/sms/config_concern.rb
# == Schema Information
#
# Table name: sms_configs
#
#  id              :bigint(8)        not null, primary key
#  delivery_method :string(255)      not null
#  template        :text(65535)      not null
#  time            :time
#  cant            :integer          default(0)
#  key             :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

require 'active_support/concern'

module Sms::ConfigConcern
  extend ActiveSupport::Concern

  included do
    has_many :messages, dependent: :destroy

    DELIVERY_METHOD_TYPES = ["Inmediato", "Un dia antes", "X dias antes"]
    
    before_validation :_delivery_method

    validates :delivery_method, presence: true, :inclusion => { :in => DELIVERY_METHOD_TYPES }
    validates :template, presence: true
    validates :cant, numericality: {only_integer: true, less_than_or_equal_to: 365, greater_than_or_equal_to: 0 }
    validates :key, presence: true, uniqueness: true
    validates_datetime :time, :if => Proc.new {|a| a.time.present?}
    validate :_cant, :if => Proc.new {|a| a.cant.present?}
    validate :template_length, :if => Proc.new {|a| a.template.present?}
  end

  private

    def template_length
      errors.add(:base, "Error: La cantidad de caracteres debe ser menor o igual a 160") if self.template.gsub(/#\w+/, "").length > 160
    end

    def _cant
      errors.add(:base, "Error: Falta ingresar la cantidad de dias") if self.delivery_method == "X dias antes" && self.cant == 0
    end

    def _delivery_method
      self.cant = 0 unless self.delivery_method == "X dias antes"
      self.time = nil if self.delivery_method == "Inmediato"
    end
end

app/models/concerns/sms/message_concern.rb
# == Schema Information
#
# Table name: sms_messages
#
#  id         :bigint(8)        not null, primary key
#  text       :text(65535)      not null
#  phone      :string(255)      not null
#  date       :datetime         not null
#  config_id  :bigint(8)        not null
#  status     :string(255)      not null
#  log        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cancel     :boolean          default(FALSE)
#

require 'active_support/concern'

module Sms::MessageConcern
  extend ActiveSupport::Concern
  
  included do
    belongs_to :config
    has_many :responses, dependent: :destroy

    STATUS_TYPES = ["success", "pending", "canceled", "fail"]

    validates :text, presence: true, length: { in: 1..160 }
    validates :config_id, presence: true
    validates :status, presence: true, :inclusion => { :in => STATUS_TYPES }
    validates :log, length: { in: 4..255 }, allow_nil: true, allow_blank: true
    validates :phone, numericality: {only_integer: true}
    validates_length_of :phone, is: 10, :if => Proc.new {|a| a.phone.present?}  
    validates_datetime :date
  end

  def valid_key? key
    return self.config.key.to_s == key.to_s
  end 

end

app/models/concerns/sms/response_concern.rb
# == Schema Information
#
# Table name: sms_responses
#
#  id         :integer          not null, primary key
#  text       :text(65535)      not null
#  message_id :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'active_support/concern'

module Sms::ResponseConcern
  extend ActiveSupport::Concern

  included do
    belongs_to :message

    validates :text, presence: true, length: { in: 4..65535 }
    validates :message_id, presence: true
  end
end

app/models/sms/application_record.rb
module Sms
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/sms/config.rb
# == Schema Information
#
# Table name: sms_configs
#
#  id              :bigint(8)        not null, primary key
#  delivery_method :string(255)      not null
#  template        :text(65535)      not null
#  time            :time
#  cant            :integer          default(0)
#  key             :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

module Sms
  class Config < ApplicationRecord
    include Sms::ConfigConcern

    # Your code goes here...

  end
end

app/models/sms/message.rb
# == Schema Information
#
# Table name: sms_messages
#
#  id         :bigint(8)        not null, primary key
#  text       :text(65535)      not null
#  phone      :string(255)      not null
#  date       :datetime         not null
#  config_id  :bigint(8)        not null
#  status     :string(255)      not null
#  log        :string(255) 
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module Sms
  class Message < ApplicationRecord
    include Sms::MessageConcern

    # Your code goes here...
    
  end
end

app/models/sms/response.rb
# == Schema Information
#
# Table name: sms_responses
#
#  id         :bigint(8)        not null, primary key
#  text       :text(65535)      not null
#  message_id :bigint(8)        not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module Sms
  class Response < ApplicationRecord
    include Sms::ResponseConcern

    # Your code goes here...
    
  end
end

app/controllers/concerns/sms/configs_controller_concern.rb
require 'active_support/concern'

module Sms::ConfigsControllerConcern
  extend ActiveSupport::Concern
  
  included do
    before_action :build_time, only:[:create, :update]
  end

  def show
    @config = Sms::Config.last
  end

  def new
    @config = Sms::Config.new
  end

  def edit
    @config = Sms::Config.last
  end

  def create
    @config = Sms::Config.new(config_params)

    if @config.save
      redirect_to config_path, notice: 'Config was successfully created.'
    else
      render :new
    end
  end

  def update
    @config = Sms::Config.last

    if @config.update(config_params)
      redirect_to config_path, notice: 'Config was successfully updated.'
    else
      render :edit
    end
  end

  private

    def build_time
      if !(params[:fixed_time].present?) || (params[:fixed_time].present? && !(params[:fixed_time] == "true"))
        (1..5).each do |index|
          params[:config].delete "time(#{index}i)"
        end
        params[:config].merge!(time: nil) 
      end
    end

    def config_params
      params.require(:config).permit(:delivery_method, :time, :template, :cant, :key)
    end
  
end

app/controllers/concerns/sms/log_controller_concern.rb
require 'active_support/concern'

module Sms::LogControllerConcern
  extend ActiveSupport::Concern
  
  included do
  end

  def index
    @messages = Sms::Message.all.order("created_at DESC")
  end

end

app/controllers/concerns/sms/messages_controller_concern.rb
require 'active_support/concern'

module Sms::MessagesControllerConcern
  extend ActiveSupport::Concern
  
  included do
  end

  def resend
    @resending = false
    message = Sms::Message.find(params[:id])

    unless message.nil?
      @resending = true

      if Sms.resend!(message).nil?
        message.update(status: "fail", log: "Error al reenviar")
      end
    end
    
    respond_to do |format|
      format.js
    end 
  end

  def cancel
    @cancelling = false
    message = Sms::Message.find(params[:id])

    unless message.nil?
      @cancelling = true

      if Sms.cancel!(message).nil?
        message.update(status: "fail", log: "Error al cancelar")
      end
    end
    
    respond_to do |format|
      format.js
    end 
  end

end

app/controllers/sms/api/v1/messages_controller.rb
require_dependency "sms/application_controller"

module Sms
  class Api::V1::MessagesController < ActionController::API

    def api_sms_status_response
      @message = Sms::Message.where(id: request.headers["IdSMS"]).first
      
      if !@message.nil? && @message.status = "success" && request.headers["token"].present? && @message.valid_key?(request.headers["token"]) && @message.update(log: request.headers["status"])
        render json: :ok, status: :ok      
      else
        render json: :fail, status: :bad_request
      end
    end

  end
end

app/controllers/sms/api/v1/responses_controller.rb
require_dependency "sms/application_controller"

module Sms
  class Api::V1::ResponsesController < ActionController::API

    def api_sms_response
      @message = Sms::Message.where(id: request.headers["IdSMS"]).first
      
      if !@message.nil? && @message.status = "success" && request.headers["token"].present? && @message.valid_key?(request.headers["token"])
        @response = @message.responses.new(text: request.headers["response"])

        if @response.save
          render json: :ok, status: :ok     
        else
          render json: :fail, status: :bad_request
        end
      else
        render json: :fail, status: :bad_request
      end
    end
  end
end

app/controllers/sms/application_controller.rb
module Sms
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

app/controllers/sms/configs_controller.rb
require_dependency "sms/application_controller"

module Sms
  class ConfigsController < ApplicationController

    include Sms::ConfigsControllerConcern

    # def show
    #   super
    # end

    # def new
    #   super
    # end

    # def edit
    #   super
    # end
    
    # def create
    #   super
    # end

    # def update
    #   super
    # end

    # private

    #   def build_time
    #     super
    #   end

    #   def config_params
    #     params.require(:config).permit(:delivery_method, :time, :template, :cant, :key)
    #   end

  end
end

app/controllers/sms/log_controller.rb
require_dependency "sms/application_controller"

module Sms
  class LogController < ApplicationController
    include Sms::LogControllerConcern

    # def show
    #   super
    # end

  end
end

app/controllers/sms/messages_controller.rb
require_dependency "sms/application_controller"

module Sms
  class MessagesController < ApplicationController
    include Sms::MessagesControllerConcern

    # def resend
    #   super
    # end
    
    # def cancel
    #   super
    # end

  end
end

app/helpers/sms/application_helper.rb
module Sms
  module ApplicationHelper
  end
end

app/views/sms/configs/_form.html.erb
<%= form_with(model: config, local: true, :url => config_path) do |form| %>
  <% if config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(config.errors.count, "error") %> prohibited this config from being saved:</h2>

      <ul>
      <% config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"m id= "config_delivery">
    <%= form.label :delivery_method %>
    <%= form.select :delivery_method, Sms::Config::DELIVERY_METHOD_TYPES %>

    <%if @config.delivery_method == "X dias antes"%>
      <div id= "cant"> 
        <%= form.label :cant %>
        <%= form.number_field :cant, min: 0, max:365 %>
      </div>
    <%else%>
      <div style="display: none;" id= "cant">
        <%= form.label :cant %>
        <%= form.number_field :cant, min: 0, max:365 %>
      </div>
    <%end%>
  </div>  
  
  <% if @config.time %>
    <div class="field" id= "config_time">
      <div> 
        <%= label_tag :fixed_time %>
        <%= check_box_tag :fixed_time, true, checked: true %>
      </div> 
      <div id= "time_select">
        <%= form.time_select :time %>
      </div>
    </div>
  <%else %>
    <% if (@config.delivery_method == "Inmediato") %>
      <div class="field" style="display: none;" id= "config_time">
        <div> 
          <%= label_tag :fixed_time %>
          <%= check_box_tag :fixed_time, true %>
        </div> 
        <div style="display: none;" id= "time_select">
          <%= form.time_select :time %>
        </div>
      </div>
    <%else%>
      <div class="field" id= "config_time">
        <div> 
          <%= label_tag :fixed_time %> 
          <%= check_box_tag :fixed_time, true %>
        </div> 
        <div style="display: none;" id= "time_select">
          <%= form.time_select :time %>
        </div>
      </div>
    <%end%>
  <%end%>

  <div class="field">
    <div> <%= form.label :template %> </div>
    <%= form.text_area :template, cols: 30, rows: 8, id: "config_text_area" %>
    <p id = "config_counter">
      <% if @config.template %>
        <%= "Characters left: #{160 - @config.template.gsub(/#\w+/, "").length}"%>
      <%else%>
        <%= "Characters left: 160"%>
      <%end%>
    </p>
  </div>

  <div class="field">
    <%= form.label :key %>
    <%= form.text_field :key %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sms/configs/edit.html.erb
<h1>Editing Config</h1>

<%= render 'form', config: @config %>

<%= link_to 'Back', config_path %>

app/views/sms/configs/new.html.erb
<h1>New Config</h1>

<%= render 'form', config: @config %>

<%= link_to 'Back', config_path %>

app/views/sms/configs/show.html.erb
<%if @config.present?%>
  <h2>SMS Config</h2>

  <p>
    <strong>Delivery_method:</strong>
    <%= @config.delivery_method %>
  </p>  

  <%if @config.delivery_method == "X dias antes"%>
    <p>
      <strong>Cant:</strong>
      <%= @config.cant %>
    </p>
  <%end%>

  <%if @config.time.present? %>
    <p>
      <strong>Fixed time:</strong>
      <%= @config.time.strftime('%H:%M') %>
    </p>
  <%end%>

  <p>
    <strong>Template:</strong>
    <%= @config.template %>
  </p>

  <p>
    <strong>key:</strong>
    <%= @config.key %>
  </p>

  <%= link_to 'Edit', edit_config_path %>
<%else%>
  <%= link_to 'New config', new_config_path %>
<%end%>